"""Ax 1.3.1 adapter for sequential morphology optimization."""

from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Literal, Mapping

from ax.adapter.registry import Generators
from ax.api.client import Client
from ax.api.configs import RangeParameterConfig
from ax.generation_strategy.generator_spec import GeneratorSpec
from ax.generation_strategy.generation_node import GenerationNode
from ax.generation_strategy.generation_strategy import GenerationStrategy
from ax.generation_strategy.transition_criterion import MinTrials
from ax.generators.torch.botorch_modular.surrogate import ModelConfig, SurrogateSpec
from botorch.acquisition.logei import qLogExpectedImprovement
from botorch.models.gp_regression import SingleTaskGP
from gpytorch.kernels import MaternKernel

from model import InvalidFingertipParameters
from optimization.design_space import DesignSpace
from optimization.evaluator import DesignEvaluation
from optimization.study import OptimizationStudy


AX_OBJECTIVE_NAME = "minimum_separability"
AxTrialPhase = Literal["baseline", "sobol", "bo"]


@dataclass(frozen=True)
class AxSettings:
    """Explicit algorithm settings for one Ax run."""

    sobol_trials: int
    bo_trials: int
    seed: int

    def __post_init__(self) -> None:
        for name, value in (
            ("sobol_trials", self.sobol_trials),
            ("bo_trials", self.bo_trials),
            ("seed", self.seed),
        ):
            if not isinstance(value, int) or isinstance(value, bool):
                raise TypeError(f"{name} must be an integer, not bool")
        if self.sobol_trials < 1:
            raise ValueError("sobol_trials must be at least 1")
        if self.bo_trials < 0:
            raise ValueError("bo_trials must be nonnegative")
        if self.seed < 0:
            raise ValueError("seed must be nonnegative")


@dataclass(frozen=True)
class AxTrialRecord:
    """One observed or failed Ax proposal."""

    trial_index: int
    phase: AxTrialPhase
    parameters: Mapping[str, float]
    evaluation: DesignEvaluation | None
    failure_message: str | None

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "parameters",
            MappingProxyType(dict(self.parameters)),
        )


@dataclass(frozen=True)
class AxRunResult:
    """Compact records from one Ax run."""

    records: tuple[AxTrialRecord, ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "records", tuple(self.records))

    @property
    def best_record(self) -> AxTrialRecord | None:
        """Return the first successful record with the largest observed score."""
        best: AxTrialRecord | None = None
        best_value: float | None = None
        for record in self.records:
            evaluation = record.evaluation
            if (
                evaluation is None
                or evaluation.status != "success"
                or evaluation.minimum_separability is None
            ):
                continue
            value = evaluation.minimum_separability
            if best is None or best_value is None or value > best_value:
                best = record
                best_value = value
        return best


def _generation_strategy(settings: AxSettings) -> GenerationStrategy:
    """Build the explicit Sobol -> Modular BoTorch strategy."""
    sobol_node = GenerationNode(
        name="Sobol",
        generator_specs=[
            GeneratorSpec(
                generator_enum=Generators.SOBOL,
                generator_kwargs={"seed": settings.seed},
            )
        ],
        transition_criteria=[
            MinTrials(
                threshold=settings.sobol_trials,
                transition_to="BoTorch",
                # The manually attached baseline is not generated by this node.
                use_all_trials_in_exp=False,
                # Count every proposed Sobol trial, including FAILED trials.
                not_in_statuses=[],
            )
        ],
    )
    model_config = ModelConfig(
        botorch_model_class=SingleTaskGP,
        covar_module_class=MaternKernel,
        covar_module_options={"nu": 2.5},
        name="SingleTaskGP-Matern52",
    )
    bo_node = GenerationNode(
        name="BoTorch",
        generator_specs=[
            GeneratorSpec(
                generator_enum=Generators.BOTORCH_MODULAR,
                generator_kwargs={
                    "surrogate_spec": SurrogateSpec(
                        model_configs=[model_config]
                    ),
                    "botorch_acqf_class": qLogExpectedImprovement,
                },
            )
        ],
    )
    return GenerationStrategy(nodes=[sobol_node, bo_node])


def _client_and_strategy(
    study: OptimizationStudy,
    settings: AxSettings,
) -> tuple[Client, GenerationStrategy]:
    parameters = [
        RangeParameterConfig(
            name=variable.name,
            bounds=(variable.lower, variable.upper),
            parameter_type="float",
        )
        for variable in study.design_space.active_variables
    ]
    strategy = _generation_strategy(settings)
    client = Client(random_seed=settings.seed)
    client.configure_experiment(parameters=parameters)
    client.configure_optimization(objective=AX_OBJECTIVE_NAME)
    client.set_generation_strategy(strategy)
    return client, strategy


def create_ax_client(
    study: OptimizationStudy,
    settings: AxSettings,
) -> Client:
    """Create an unexecuted Ax experiment from active design variables."""
    if not isinstance(study, OptimizationStudy):
        raise TypeError("study must be an OptimizationStudy")
    if not isinstance(settings, AxSettings):
        raise TypeError("settings must be AxSettings")
    client, _ = _client_and_strategy(study, settings)
    return client


def _failure_message(evaluation: DesignEvaluation) -> str:
    return evaluation.failure_message or (
        f"DesignEvaluator returned status {evaluation.status!r}"
    )


def _mark_failed(client: Client, trial_index: int, message: str) -> None:
    client.mark_trial_failed(trial_index=trial_index, failed_reason=message)


def _attempt_mark_failed(
    client: Client,
    trial_index: int,
    message: str,
) -> None:
    """Attempt failure reporting without replacing an original exception."""
    try:
        _mark_failed(client, trial_index, message)
    except Exception:
        pass


def _evaluate_trial(
    client: Client,
    evaluator: object,
    design_space: DesignSpace,
    trial_index: int,
    phase: AxTrialPhase,
    candidate: Mapping[str, float],
) -> AxTrialRecord:
    """Decode, evaluate, and report one already-created Ax trial."""
    parameters = dict(candidate)
    try:
        try:
            decoded = design_space.decode(parameters)
        except InvalidFingertipParameters as exc:
            message = f"InvalidFingertipParameters: {exc}"
            _mark_failed(client, trial_index, message)
            return AxTrialRecord(
                trial_index=trial_index,
                phase=phase,
                parameters=parameters,
                evaluation=None,
                failure_message=message,
            )

        evaluation = evaluator.evaluate(decoded)  # type: ignore[attr-defined]
        if evaluation.status != "success":
            message = _failure_message(evaluation)
            _mark_failed(client, trial_index, message)
            return AxTrialRecord(
                trial_index=trial_index,
                phase=phase,
                parameters=parameters,
                evaluation=evaluation,
                failure_message=message,
            )

        value = evaluation.minimum_separability
        if value is None:
            raise ValueError(
                "successful DesignEvaluation has no minimum_separability"
            )
        client.complete_trial(
            trial_index=trial_index,
            raw_data={AX_OBJECTIVE_NAME: (value, 0.0)},
        )
        return AxTrialRecord(
            trial_index=trial_index,
            phase=phase,
            parameters=parameters,
            evaluation=evaluation,
            failure_message=None,
        )
    except Exception as exc:
        _attempt_mark_failed(client, trial_index, f"{type(exc).__name__}: {exc}")
        raise


def _generate_one(
    client: Client,
    strategy: GenerationStrategy,
    phase: AxTrialPhase,
    proposal_number: int,
) -> tuple[int, Mapping[str, float]]:
    expected_node = "Sobol" if phase == "sobol" else "BoTorch"
    try:
        generated = client.get_next_trials(max_trials=1)
    except Exception as exc:
        raise RuntimeError(
            f"Ax could not generate {phase} proposal {proposal_number}: {exc}"
        ) from exc
    if len(generated) != 1:
        for trial_index in generated:
            _attempt_mark_failed(
                client,
                trial_index,
                f"Ax returned an invalid {phase} generation result",
            )
        raise RuntimeError(
            f"Ax generated {len(generated)} {phase} proposals for request "
            f"{proposal_number}; expected exactly one"
        )
    if strategy.current_node_name != expected_node:
        trial_index, _ = next(iter(generated.items()))
        _attempt_mark_failed(
            client,
            trial_index,
            f"Ax generated from unexpected node {strategy.current_node_name!r}",
        )
        raise RuntimeError(
            f"Ax generated proposal {proposal_number} from node "
            f"{strategy.current_node_name!r}, expected {expected_node!r}"
        )
    trial_index, parameters = next(iter(generated.items()))
    return trial_index, parameters


def run_ax_optimization(
    study: OptimizationStudy,
    settings: AxSettings,
) -> AxRunResult:
    """Run baseline, sequential Sobol proposals, then sequential BO proposals."""
    if not isinstance(study, OptimizationStudy):
        raise TypeError("study must be an OptimizationStudy")
    if not isinstance(settings, AxSettings):
        raise TypeError("settings must be AxSettings")

    client, strategy = _client_and_strategy(study, settings)
    evaluator = study.create_evaluator()
    records: list[AxTrialRecord] = []

    baseline_values = {
        variable.name: getattr(study.design_space.baseline, variable.name)
        for variable in study.design_space.active_variables
    }
    baseline_trial = client.attach_trial(
        parameters=baseline_values,
        arm_name="baseline",
    )
    records.append(
        _evaluate_trial(
            client,
            evaluator,
            study.design_space,
            baseline_trial,
            "baseline",
            baseline_values,
        )
    )

    for proposal_number in range(1, settings.sobol_trials + 1):
        trial_index, candidate = _generate_one(
            client, strategy, "sobol", proposal_number
        )
        records.append(
            _evaluate_trial(
                client,
                evaluator,
                study.design_space,
                trial_index,
                "sobol",
                candidate,
            )
        )

    for proposal_number in range(1, settings.bo_trials + 1):
        trial_index, candidate = _generate_one(
            client, strategy, "bo", proposal_number
        )
        records.append(
            _evaluate_trial(
                client,
                evaluator,
                study.design_space,
                trial_index,
                "bo",
                candidate,
            )
        )

    return AxRunResult(records=tuple(records))


__all__ = [
    "AX_OBJECTIVE_NAME",
    "AxRunResult",
    "AxSettings",
    "AxTrialPhase",
    "AxTrialRecord",
    "create_ax_client",
    "run_ax_optimization",
]
